# Common Labels
labels:
  app: "egov-persister"
  group: "core"

# Init Containers Configs
initContainers:
  gitSync:
    enabled: true
    repo: "git@github.com:Ramesh-Kumhar/configs"
    branch: "UNIFIED-DEV"

# Container Configs
image:
  repository: "egov-persister"
  tag: DIGIT-2.9-LTS-07f47790b8-8
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/common-persist/health"
  readinessProbePath: "/common-persist/health"
appType: "java-spring"
tracing-enabled: true
persist-yml-path: "file:///work-dir/configs/egov-persister/mdms-persister.yml,file:///work-dir/configs/egov-persister/benefits-app-persistor.yml"
heap: "-Xmx192m -Xms192m"
memory_limits: 512Mi
java-args: ""

# Additional Container Envs
env: |
  - name: EGOV_PERSIST_YML_REPO_PATH
    value: {{ index .Values "persist-yml-path" | quote }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: JAEGER_SAMPLER_PARAM
    value: "1"
