#checking helmfile
helmfiles:
  - path: ./charts/backbone-services/backboneservices-helmfile.yaml
  - path: ./charts/core-services/coreservices-helmfile.yaml
  - path: ./charts/uba/uba_helmfile.yaml


